
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon May 19 22:04:46 CEST 2025
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int INTERROG = 56;
  public static final int DOSPUNTOS = 55;
  public static final int WHEN = 28;
  public static final int RASIG = 59;
  public static final int POR = 40;
  public static final int CCIERRE = 66;
  public static final int PCIERRE = 64;
  public static final int LCIERRE = 68;
  public static final int LAP = 67;
  public static final int USING = 24;
  public static final int CASE = 27;
  public static final int CAP = 65;
  public static final int CONTINUE = 26;
  public static final int REPEAT = 17;
  public static final int INT = 18;
  public static final int ARRAY = 33;
  public static final int REF = 53;
  public static final int FOR = 16;
  public static final int NUMENT = 36;
  public static final int AND = 44;
  public static final int NOT = 43;
  public static final int IGUAL = 46;
  public static final int RECORD = 8;
  public static final int OR = 45;
  public static final int BOOL = 21;
  public static final int DIV = 41;
  public static final int READI = 31;
  public static final int MASIG = 60;
  public static final int READF = 32;
  public static final int MAIN = 34;
  public static final int IF = 12;
  public static final int EOF = 0;
  public static final int ASIG = 57;
  public static final int RETURN = 4;
  public static final int TRUE = 22;
  public static final int NEW = 5;
  public static final int error = 1;
  public static final int COMA = 70;
  public static final int EXPORT = 10;
  public static final int MENOS = 39;
  public static final int MENOR = 49;
  public static final int NULL = 7;
  public static final int MOD = 42;
  public static final int BREAK = 25;
  public static final int MOASIG = 62;
  public static final int DESIGUAL = 47;
  public static final int PCOMA = 69;
  public static final int NUMREAL = 37;
  public static final int MAYOR = 48;
  public static final int REAL = 19;
  public static final int IMPORT = 11;
  public static final int MODULE = 9;
  public static final int PAP = 63;
  public static final int NONE = 3;
  public static final int ELSE = 14;
  public static final int PUNTO = 54;
  public static final int MAYORIG = 50;
  public static final int FUNC = 2;
  public static final int ENUM = 20;
  public static final int IDEN = 35;
  public static final int WHILE = 15;
  public static final int SASIG = 58;
  public static final int ACCESO = 52;
  public static final int DEFAULT = 29;
  public static final int MENORIG = 51;
  public static final int DEL = 6;
  public static final int DASIG = 61;
  public static final int FALSE = 23;
  public static final int ELIF = 13;
  public static final int PRINT = 30;
  public static final int MAS = 38;
}

